### ISSUE TITLE
ubuntu 16.04 issue

### ISSUE THREAD

**Issue by NicolaFr** [mad-de/simple_openMVG#1]
Hi, following the instruction [here](https://raw.githubusercontent.com/openMVG/openMVG/master/BUILD) I compiled openMVG under ubuntu 16.04; then following the instruction [here](https://github.com/mad-de/simple_openMVG) I can run the simple gui, but when I click "begin workflow" I get this error 
"
('Using input dir  : ', '/home/n1k0l4/Desktop/carabina/foto')
('      output_dir : ', '/home/n1k0l4/Desktop/carabina/foto_out')
1. Image listing - generate sfm_data.json

Traceback (most recent call last):
  File "workflow.py", line 82, in <module>
    pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-c", "3"] )
  File "/usr/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
"

is there a way to solve?

thanks, N1k0l4

**Comment by mad-de** [comment]
Hi Nicola,

i ceased working on this project in favor of https://github.com/open-anatomy/SfM_gui_for_openMVG which I would recommend you to use. It`s easier to install, use and adds a lot of options.

As for your problem - if you do not wish to switch to the SfM gui - can you give me a list of files in your OpenMVS_build/bin/ folder?

best wishes!

**Comment by NicolaFr** [comment]
thanks for fast reply!!

I try to use Sfm gui, but running "make" for OpenMVG I get an error when I'm at about 88% of making, so i decided to switch (if can be useful I can run again the whole process and send you the exact moment of the error)

For simple_gui, I haven't a OpenMVS folder, because I only build OpenMVG..

**Comment by mad-de** [comment]
I would recommend using the openMVG gui, so if you could open up an Issue there with the exact error, I can try sorting it out over the next days, although I`m afraid that might take me a while. 

If you have the option to set up a second partition, you might like to try to use Ubuntu 15.10 where it is tested and I know that it`s running alright. The newest version of ArcheOS (Hypatia) also includes the newest GUI, but I`m not sure if it is already available for download,

**Comment by NicolaFr** [comment]
I try again with openMVG gui following the steps [here](https://github.com/open-anatomy/SfM_gui_for_openMVG/blob/master/BUILD.md) and on _cmake . ../openMVS -DCMAKE_BUILD_TYPE=Release -DVCG_DIR="$main_path/vcglib"_ i get this:

_-- cotire 1.7.8 loaded.
-- Detected version of GNU GCC: 53 (503)
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Can't find CUDA. Continuing without it.
-- WARNING: BREAKPAD was not found: Please specify BREAKPAD directory using BREAKPAD_ROOT env. variable
-- Can't find BreakPad. Continuing without it.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   iostreams
--   program_options
--   system
--   serialization
--   regex
-- Eigen 3.2.92 found (include: /usr/include/eigen3)
-- OpenCV 2.4.9.1 found (include: /usr/include/opencv;/usr/include)
-- CXX target Common cotired without unity build.
-- CXX target Math cotired without unity build.
-- CXX target IO cotired without unity build.
-- CGAL 4.7 found (include: /usr/include)
CMake Error at build/Utils.cmake:216 (message):
  VCG required, but not found: Please specify VCG directory using VCG_ROOT
  env.  variable
Call Stack (most recent call first):
  build/Modules/FindVCG.cmake:23 (package_report_not_found)
  libs/MVS/CMakeLists.txt:9 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/n1k0l4/openMVS_build/CMakeFiles/CMakeOutput.log"._

Here attached the log 
[CMakeOutput.txt](https://github.com/mad-de/simple_openMVG/files/355635/CMakeOutput.txt)

**Comment by mad-de** [comment]
Hi! Can you switch to https://github.com/open-anatomy/SfM_gui_for_openMVG for your issue please?

If openMVS is not running correctly, the GUI should still work alright for now - you can use cmvs-pmvs instead - could you check that please.
